{
  'encrypted_username': 'place your username encrypted with EncryptionUtils using your key',
  'encrypted_password': 'place your password encrypted with EncryptionUtils using your key',
  'key': '80a003040c0807d00f01075090123456'
}

